# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('type', models.CharField(default='garden', max_length=10)),
                ('time_placed', models.DateTimeField(auto_now_add=True)),
                ('placed_by', models.IntegerField()),
            ],
        ),
    ]
